/**
 * WikiService - Renderer-side service for link classification and graph lookups.
 * Consumes the wiki-index.json generated by the server.
 */
(function () {
  let index = null;
  let isInitialized = false;

  const WikiService = {
    /**
     * Tải và cache dữ liệu wiki index từ server.
     */
    async init() {
      // Avoid fetch if wiki scanner is not enabled to prevent 404 in console
      const ws = window.AppState?.currentWorkspace;
      if (!ws?.wikiScanner?.enabled) {
        index = null;
        isInitialized = false;
        return false;
      }

      try {
        const response = await fetch('/api/wiki/index');
        if (!response.ok) {
          throw new Error('Wiki index not found or Wiki Scanner not enabled.');
        }
        index = await response.json();
        isInitialized = true;
        return true;
      } catch (_err) {
        // Silently fail if wiki index is not available
        index = null;
        isInitialized = false;
        return false;
      }
    },

    /**
     * Phân loại một liên kết (href) dựa trên ngữ cảnh file hiện tại.
     * @param {string} href - Giá trị href của link.
     * @param {string} currentRelativePath - Path của file đang hiển thị (relative to vault root).
     */
    classifyLink(href, currentRelativePath) {
      if (!href) return { type: 'unknown' };

      // 1. External Link
      if (href.startsWith('http://') || href.startsWith('https://') || href.startsWith('mailto:') || href.startsWith('tel:')) {
        return { type: 'external', url: href };
      }

      // 2. Anchor Link (trong cùng file)
      if (href.startsWith('#')) {
        return { type: 'anchor', anchor: href };
      }

      // Tách hash fragment nếu có (ví dụ: file.md#heading-1)
      let [pathPart, hashPart] = href.split('#');
      const anchor = hashPart ? '#' + hashPart : null;

      // 3. Smart Path Resolution (Ưu tiên xử lý đường dẫn tương đối trước khi check Index)
      if (pathPart.startsWith('./') || pathPart.startsWith('../') || pathPart.endsWith('.md')) {
        const isRootRelative = !pathPart.startsWith('./') && !pathPart.startsWith('../') && index && (
          (index.all_paths && index.all_paths.includes(pathPart)) ||
          (index.path_to_id && index.path_to_id[pathPart] !== undefined)
        );

        const resolvedPath = isRootRelative ? pathPart : this._resolvePath(currentRelativePath, pathPart);
        const id = index ? index.path_to_id[resolvedPath] : null;

        return {
          type: 'internal',
          resolvedPath: resolvedPath,
          anchor: anchor,
          id: id || null
        };
      }

      // 4. ID-based (Cần Index để tra cứu)
      if (index && index.id_to_path[pathPart]) {
        return {
          type: 'internal',
          resolvedPath: index.id_to_path[pathPart],
          anchor: anchor,
          id: pathPart
        };
      }

      return { type: 'unknown' };
    },

    /**
     * Lấy danh sách liên kết ngược cho một ID hoặc Path.
     */
    getBacklinks(idOrPath) {
      if (!index) return [];

      // Nếu là path, thử tìm ID tương ứng trước
      const id = index.path_to_id[idOrPath] || idOrPath;
      const backlinkIds = index.backlinks[id] || [];

      return backlinkIds.map(sourceId => {
        const path = index.id_to_path[sourceId] || sourceId;
        return {
          id: sourceId,
          path: path,
          title: this._extractTitleFromPath(path)
        };
      });
    },

    /**
     * Lấy danh sách liên kết đi cho một Path.
     */
    getOutgoing(relativePath) {
      if (!index || !index.outgoing[relativePath]) return null;
      return index.outgoing[relativePath];
    },

    isReady() {
      return isInitialized && index !== null;
    },

    /**
     * Giải quyết đường dẫn tương đối thành đường dẫn chuẩn trong Vault.
     */
    _resolvePath(currentPath, relativeHref) {
      // 1. Lấy mảng các thư mục của file hiện tại
      const parts = currentPath.split('/').filter(p => p);
      parts.pop(); // Xóa tên file để lấy folder

      // 2. Tách link tương đối (loại bỏ query params hoặc anchor nếu có)
      const cleanHref = relativeHref.split('#')[0].split('?')[0];
      const relParts = cleanHref.split('/').filter(p => p);

      for (const part of relParts) {
        if (part === '.') continue;
        if (part === '..') {
          if (parts.length > 0) parts.pop();
        } else {
          parts.push(part);
        }
      }

      return parts.join('/');
    },

    _extractTitleFromPath(filePath) {
      const filename = filePath.split('/').pop();
      return filename.replace(/\.md$/, '');
    }
  };

  // Export to window
  window.WikiService = WikiService;
})();
